name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
      - name: Build and Test
        working-directory: ./src
        run: ./Build.ps1
        shell: pwsh
      - name: Push to MyGet
        working-directory: ./src
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_CI_API_KEY }}
        run: ./Push.ps1
        shell: pwsh
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/**/*
